/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISalesOrderChecker,
  ISalesOrderCheckerInterface,
} from "../../contracts/ISalesOrderChecker";

const _abi = [
  {
    inputs: [],
    name: "verify",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class ISalesOrderChecker__factory {
  static readonly abi = _abi;
  static createInterface(): ISalesOrderCheckerInterface {
    return new utils.Interface(_abi) as ISalesOrderCheckerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISalesOrderChecker {
    return new Contract(address, _abi, signerOrProvider) as ISalesOrderChecker;
  }
}
