/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace Marketplace {
  export type SalesOrderStruct = {
    contractAddress: PromiseOrValue<string>;
    tokenId: PromiseOrValue<BigNumberish>;
    tokenOwner: PromiseOrValue<string>;
    price: PromiseOrValue<BigNumberish>;
    tokenURI: PromiseOrValue<string>;
    signature: PromiseOrValue<BytesLike>;
  };

  export type SalesOrderStructOutput = [
    string,
    BigNumber,
    string,
    BigNumber,
    string,
    string
  ] & {
    contractAddress: string;
    tokenId: BigNumber;
    tokenOwner: string;
    price: BigNumber;
    tokenURI: string;
    signature: string;
  };
}

export interface SalesOrderCheckerInterface extends utils.Interface {
  functions: {
    "verify((address,uint256,address,uint256,string,bytes))": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "verify"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verify",
    values: [Marketplace.SalesOrderStruct]
  ): string;

  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {};
}

export interface SalesOrderChecker extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SalesOrderCheckerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    verify(
      _salesOrder: Marketplace.SalesOrderStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  verify(
    _salesOrder: Marketplace.SalesOrderStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    verify(
      _salesOrder: Marketplace.SalesOrderStruct,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    verify(
      _salesOrder: Marketplace.SalesOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    verify(
      _salesOrder: Marketplace.SalesOrderStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
